# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import channelescrow_pb2 as channelescrow__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in channelescrow_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ChannelEscrowStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FreezeChannel = channel.unary_unary(
                '/channelescrowrpc.ChannelEscrow/FreezeChannel',
                request_serializer=channelescrow__pb2.FreezeChannelRequest.SerializeToString,
                response_deserializer=channelescrow__pb2.FreezeChannelResponse.FromString,
                _registered_method=True)
        self.PrepareParent = channel.unary_unary(
                '/channelescrowrpc.ChannelEscrow/PrepareParent',
                request_serializer=channelescrow__pb2.PrepareParentRequest.SerializeToString,
                response_deserializer=channelescrow__pb2.PrepareParentResponse.FromString,
                _registered_method=True)
        self.BeginSigning = channel.unary_unary(
                '/channelescrowrpc.ChannelEscrow/BeginSigning',
                request_serializer=channelescrow__pb2.BeginSigningRequest.SerializeToString,
                response_deserializer=channelescrow__pb2.BeginSigningResponse.FromString,
                _registered_method=True)
        self.SignParent = channel.unary_unary(
                '/channelescrowrpc.ChannelEscrow/SignParent',
                request_serializer=channelescrow__pb2.SignParentRequest.SerializeToString,
                response_deserializer=channelescrow__pb2.SignParentResponse.FromString,
                _registered_method=True)
        self.FinalizeParent = channel.unary_unary(
                '/channelescrowrpc.ChannelEscrow/FinalizeParent',
                request_serializer=channelescrow__pb2.FinalizeParentRequest.SerializeToString,
                response_deserializer=channelescrow__pb2.FinalizeParentResponse.FromString,
                _registered_method=True)
        self.Status = channel.unary_unary(
                '/channelescrowrpc.ChannelEscrow/Status',
                request_serializer=channelescrow__pb2.StatusRequest.SerializeToString,
                response_deserializer=channelescrow__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.Cancel = channel.unary_unary(
                '/channelescrowrpc.ChannelEscrow/Cancel',
                request_serializer=channelescrow__pb2.CancelRequest.SerializeToString,
                response_deserializer=channelescrow__pb2.CancelResponse.FromString,
                _registered_method=True)


class ChannelEscrowServicer:
    """Missing associated documentation comment in .proto file."""

    def FreezeChannel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PrepareParent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BeginSigning(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SignParent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FinalizeParent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Cancel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChannelEscrowServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FreezeChannel': grpc.unary_unary_rpc_method_handler(
                    servicer.FreezeChannel,
                    request_deserializer=channelescrow__pb2.FreezeChannelRequest.FromString,
                    response_serializer=channelescrow__pb2.FreezeChannelResponse.SerializeToString,
            ),
            'PrepareParent': grpc.unary_unary_rpc_method_handler(
                    servicer.PrepareParent,
                    request_deserializer=channelescrow__pb2.PrepareParentRequest.FromString,
                    response_serializer=channelescrow__pb2.PrepareParentResponse.SerializeToString,
            ),
            'BeginSigning': grpc.unary_unary_rpc_method_handler(
                    servicer.BeginSigning,
                    request_deserializer=channelescrow__pb2.BeginSigningRequest.FromString,
                    response_serializer=channelescrow__pb2.BeginSigningResponse.SerializeToString,
            ),
            'SignParent': grpc.unary_unary_rpc_method_handler(
                    servicer.SignParent,
                    request_deserializer=channelescrow__pb2.SignParentRequest.FromString,
                    response_serializer=channelescrow__pb2.SignParentResponse.SerializeToString,
            ),
            'FinalizeParent': grpc.unary_unary_rpc_method_handler(
                    servicer.FinalizeParent,
                    request_deserializer=channelescrow__pb2.FinalizeParentRequest.FromString,
                    response_serializer=channelescrow__pb2.FinalizeParentResponse.SerializeToString,
            ),
            'Status': grpc.unary_unary_rpc_method_handler(
                    servicer.Status,
                    request_deserializer=channelescrow__pb2.StatusRequest.FromString,
                    response_serializer=channelescrow__pb2.StatusResponse.SerializeToString,
            ),
            'Cancel': grpc.unary_unary_rpc_method_handler(
                    servicer.Cancel,
                    request_deserializer=channelescrow__pb2.CancelRequest.FromString,
                    response_serializer=channelescrow__pb2.CancelResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'channelescrowrpc.ChannelEscrow', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('channelescrowrpc.ChannelEscrow', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChannelEscrow:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def FreezeChannel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/channelescrowrpc.ChannelEscrow/FreezeChannel',
            channelescrow__pb2.FreezeChannelRequest.SerializeToString,
            channelescrow__pb2.FreezeChannelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PrepareParent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/channelescrowrpc.ChannelEscrow/PrepareParent',
            channelescrow__pb2.PrepareParentRequest.SerializeToString,
            channelescrow__pb2.PrepareParentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BeginSigning(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/channelescrowrpc.ChannelEscrow/BeginSigning',
            channelescrow__pb2.BeginSigningRequest.SerializeToString,
            channelescrow__pb2.BeginSigningResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SignParent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/channelescrowrpc.ChannelEscrow/SignParent',
            channelescrow__pb2.SignParentRequest.SerializeToString,
            channelescrow__pb2.SignParentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FinalizeParent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/channelescrowrpc.ChannelEscrow/FinalizeParent',
            channelescrow__pb2.FinalizeParentRequest.SerializeToString,
            channelescrow__pb2.FinalizeParentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/channelescrowrpc.ChannelEscrow/Status',
            channelescrow__pb2.StatusRequest.SerializeToString,
            channelescrow__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Cancel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/channelescrowrpc.ChannelEscrow/Cancel',
            channelescrow__pb2.CancelRequest.SerializeToString,
            channelescrow__pb2.CancelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
